disk: /dev/sda
hostname: shadowarch
username: user
password: password
root_password: root
timezone: Europe/Madrid
keymap: es
locale: es_ES.UTF-8
packages:
  - git
  - firefox
  - htop
  - fastfetch
  - hyprland
  - waybar
  - wofi
  - kitty
  - vim
  - networkmanager
  - sudo
  - os-prober
  - sddm
  - openssh
  - apache
  # Graphics & Drivers
  - mesa
  - vulkan-intel
  - vulkan-radeon
  - vulkan-swrast
  - xf86-video-amdgpu
  - xf86-video-ati
  - xf86-video-nouveau
  - xf86-video-fbdev
  - nvidia
  - nvidia-utils
  - egl-wayland
  - virtualbox-guest-utils
  # Essential Audio & UI
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - wireplumber
  - ttf-jetbrains-mono
  - ttf-font-awesome
  - otf-font-awesome
  - nwg-look
  - qt5ct
  - papirus-icon-theme
  - dunst
  - polkit-kde-agent
  - thunar
  - thunar-archive-plugin
  - xdg-user-dirs # Standard folders (Downloads, etc)
